FROM python:3.11-slim

# Code here is executed as root

RUN useradd -u 8879 -m calici
RUN mkdir /app
COPY ./src /app
RUN chown -R calici:calici /app

# Code here is executed as user
USER calici
WORKDIR /app
ENTRYPOINT ["python3", "/app/run.py"]