[tool.poetry]
name = "socket"
version = "0.1.0"
description = ""
authors = ["naxhax <nathan@calici.co>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
websockets = "^12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
